(() => {
  'use strict';
  const important=new Set(['TARGET_REACHED','SESSION_RECOVERED','SESSION_RECOVERY_FAILED','CIRCUIT_BREAKER','RECIPE_COMPLETE','JOB_STOPPED','SCHEDULE_STARTED']);
  function b64(s){const pad='='.repeat((4-s.length%4)%4),base64=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
  async function enable(){if(!('Notification'in window)||!('serviceWorker'in navigator))throw new Error('Notification tidak didukung browser ini.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission tidak diberikan.');const reg=await navigator.serviceWorker.ready;const keyRes=await fetch('/api/bot/push/public-key',{cache:'no-store'});const keyData=await keyRes.json();if(!keyData.enabled||!keyData.public_key){localStorage.setItem('ns_local_notifications','1');return{mode:'local'};}let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(keyData.public_key)});const s=window.NinjaSession?.get?.();if(!s?.sessionkey)throw new Error('Login terlebih dahulu.');const r=await fetch('/api/bot/push/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({char_id:s.char_id,sessionkey:s.sessionkey,subscription:sub.toJSON()})});if(!r.ok)throw new Error('Server push subscription gagal.');localStorage.setItem('ns_local_notifications','1');return{mode:'web-push'};}
  async function localNotify(event){if(localStorage.getItem('ns_local_notifications')!=='1'||Notification.permission!=='granted'||!important.has(event?.type)||!document.hidden)return;const reg=await navigator.serviceWorker.ready;await reg.showNotification('Ninja Sage Control Center',{body:String(event.data?.message||event.type.replaceAll('_',' ')),icon:'/panel/assets/icon-192.png',tag:`ninja-${event.type}`,data:{url:'/panel/'}});}
  function ensure(){const settings=document.getElementById('btn-settings');if(!settings||document.getElementById('btn-notifications'))return;const btn=document.createElement('button');btn.id='btn-notifications';btn.className='btn btn-toggle';btn.title='Notifications';btn.innerHTML='<i class="fa-solid fa-bell"></i>';settings.insertAdjacentElement('afterend',btn);btn.onclick=async()=>{try{const r=await enable();window.NinjaUI?.toast(`Notifications enabled (${r.mode}).`,'info');}catch(e){window.NinjaUI?.toast(e.message,'warn');}};}
  window.addEventListener('ns:cloud-event',e=>localNotify(e.detail));
  navigator.serviceWorker?.addEventListener?.('message',e=>{if(e.data?.type==='push-event'){window.dispatchEvent(new CustomEvent('ns:cloud-event',{detail:{type:e.data.data?.event||'PUSH_NOTIFICATION',ts:Date.now()/1000,data:{message:e.data.data?.body||''}}}));}});
  document.addEventListener('DOMContentLoaded',ensure);window.NinjaNotifications={enable};
})();
